// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: DHT22

#include "ui.h"
lv_chart_series_t * ui_TempHumiChart_series_1 = NULL;
lv_chart_series_t * ui_TempHumiChart_series_2 = NULL;

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_temp, &ui_img_temperature_png);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 556
    lv_obj_set_x(ui_temp, -128);
    lv_obj_set_y(ui_temp, -75);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_temp, 20);

    ui_humi = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_humi, &ui_img_humidity_png);
    lv_obj_set_width(ui_humi, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_humi, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_humi, 39);
    lv_obj_set_y(ui_humi, -78);
    lv_obj_set_align(ui_humi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_humi, 45);

    ui_temperture = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperture, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperture, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperture, -53);
    lv_obj_set_y(ui_temperture, -73);
    lv_obj_set_align(ui_temperture, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperture, "25*C");
    lv_obj_set_style_text_color(ui_temperture, lv_color_hex(0x58A1FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperture, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperture, &ui_font_Zendots22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humi = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Humi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humi, 110);
    lv_obj_set_y(ui_Humi, -75);
    lv_obj_set_align(ui_Humi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humi, "50%");
    lv_obj_set_style_text_color(ui_Humi, lv_color_hex(0x20B512), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humi, &ui_font_Zendots22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempHumiChart = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_TempHumiChart, 244);
    lv_obj_set_height(ui_TempHumiChart, 132);
    lv_obj_set_x(ui_TempHumiChart, -2);
    lv_obj_set_y(ui_TempHumiChart, 32);
    lv_obj_set_align(ui_TempHumiChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_TempHumiChart, LV_CHART_TYPE_BAR);
    lv_chart_set_range(ui_TempHumiChart, LV_CHART_AXIS_PRIMARY_Y, 0, 70);
    lv_chart_set_axis_tick(ui_TempHumiChart, LV_CHART_AXIS_PRIMARY_X, 1, 5, 10, 5, true, 50);
    lv_chart_set_axis_tick(ui_TempHumiChart, LV_CHART_AXIS_PRIMARY_Y, 5, 6, 8, 3, true, 50);
    lv_chart_set_axis_tick(ui_TempHumiChart, LV_CHART_AXIS_SECONDARY_Y, 15, 5, 8, 3, true, 25);
    ui_TempHumiChart_series_1 = lv_chart_add_series(ui_TempHumiChart, lv_color_hex(0x2E96F7),
                                                                        LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_TempHumiChart_series_1_array[9] = { 0 };
    lv_chart_set_ext_y_array(ui_TempHumiChart, ui_TempHumiChart_series_1, ui_TempHumiChart_series_1_array);
    ui_TempHumiChart_series_2 = lv_chart_add_series(ui_TempHumiChart, lv_color_hex(0x26BB26),
                                                                        LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_TempHumiChart_series_2_array[9] = { 0 };
    lv_chart_set_ext_y_array(ui_TempHumiChart, ui_TempHumiChart_series_2, ui_TempHumiChart_series_2_array);




}
